services:
  mongodb:
    image: mongo:8.2.5
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    entrypoint:
      - /bin/sh
      - -c
      - |
        export MONGO_INITDB_ROOT_USERNAME="$${DB_USERNAME:?DB_USERNAME is required}"
        export MONGO_INITDB_ROOT_PASSWORD="$${DB_PASSWORD:?DB_PASSWORD is required}"
        exec docker-entrypoint.sh mongod --bind_ip_all
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
